let handler = m => m

handler.before = function (m) {
    let user = global.db.data.users[m.sender]
    let role = (user.level <= 3) ? 'محارب العنيد V'
      : ((user.level >= 3) && (user.level <= 6)) ? 'محارب الفولاذ IV'
      : ((user.level >= 6) && (user.level <= 9)) ? 'محارب الظلال III'
      : ((user.level >= 9) && (user.level <= 12)) ? 'محارب العاصفة II'
      : ((user.level >= 12) && (user.level <= 15)) ? 'محارب التنين I'
      : ((user.level >= 15) && (user.level <= 18)) ? 'النخبة الأسطورية V'
      : ((user.level >= 18) && (user.level <= 21)) ? 'النخبة الغامضة IV'
      : ((user.level >= 21) && (user.level <= 24)) ? 'النخبة المحترفة III'
      : ((user.level >= 24) && (user.level <= 27)) ? 'النخبة المدمرة II'
      : ((user.level >= 27) && (user.level <= 30)) ? 'النخبة الفتاكة I'
      : ((user.level >= 30) && (user.level <= 33)) ? 'أساتذة القوة V'
      : ((user.level >= 33) && (user.level <= 36)) ? 'أساتذة الفنون القتالية IV'
      : ((user.level >= 36) && (user.level <= 39)) ? 'أساتذة الظلام III'
      : ((user.level >= 39) && (user.level <= 42)) ? 'أساتذة الحرب II'
      : ((user.level >= 42) && (user.level <= 45)) ? 'أساتذة الخلود I'
      : ((user.level >= 45) && (user.level <= 48)) ? 'المايسترو الأعظم V'
      : ((user.level >= 48) && (user.level <= 51)) ? 'المايسترو القوي IV'
      : ((user.level >= 51) && (user.level <= 54)) ? 'المايسترو المرعب III'
      : ((user.level >= 54) && (user.level <= 57)) ? 'المايسترو المهيب II'
      : ((user.level >= 57) && (user.level <= 60)) ? 'المايسترو الفذ I'
      : ((user.level >= 60) && (user.level <= 63)) ? 'الملحمي الأعظم V'
      : ((user.level >= 63) && (user.level <= 66)) ? 'الملحمي المهيب IV'
      : ((user.level >= 66) && (user.level <= 69)) ? 'الملحمي المجيد III'
      : ((user.level >= 69) && (user.level <= 71)) ? 'الملحمي الشجاع II'
      : ((user.level >= 71) && (user.level <= 74)) ? 'الملحمي الفخم I'
      : ((user.level >= 74) && (user.level <= 77)) ? 'أسطورة العهد V'
      : ((user.level >= 77) && (user.level <= 80)) ? 'أسطورة القتال IV'
      : ((user.level >= 80) && (user.level <= 83)) ? 'أسطورة النصر III'
      : ((user.level >= 83) && (user.level <= 86)) ? 'أسطورة الظلال II'
      : ((user.level >= 86) && (user.level <= 89)) ? 'أسطورة الدم I'
      : ((user.level >= 89) && (user.level <= 91)) ? 'الأسطوري الأعظم V'
      : ((user.level >= 91) && (user.level <= 94)) ? 'الأسطوري القوي IV'
      : ((user.level >= 94) && (user.level <= 97)) ? 'الأسطوري الشرس III'
      : ((user.level >= 97) && (user.level <= 100)) ? 'الأسطوري الفتاك II'
      : ((user.level >= 100) && (user.level <= 105)) ? 'الأسطوري المهيب I'      
      : ((user.level >= 105) && (user.level <= 120)) ? 'مجد الأساطير'
      : ((user.level >= 120) && (user.level <= 150)) ? 'الزمرّد الأسطوري V'
      : ((user.level >= 150) && (user.level <= 160)) ? 'الزمرّد النادر VI'
      : ((user.level >= 160) && (user.level <= 170)) ? 'الزمرّد الملكي III'
      : ((user.level >= 170) && (user.level <= 185)) ? 'الزمرّد القوي II'
      : ((user.level >= 185) && (user.level <= 200)) ? 'الزمرّد المقدس I'
      : ((user.level >= 200) && (user.level <= 400)) ? 'التيتان الجبار III'
      : ((user.level >= 405) && (user.level <= 700)) ? 'التيتان المهيب II'
      : ((user.level >= 700) && (user.level <= 1000)) ? 'التيتان القوي I'
      : 'ملك التنين النجم'

    user.role = role
    return true
}

export default handler
